"""Generate neolink.toml from the camera store.

Neolink reads a TOML config describing the RTSP bind and one [[cameras]] block per
camera. We render it from the store so the GUI never makes the user touch TOML by hand.

TOML schema confirmed against the actual pinned source (src/config.rs at commit
6e05e7844b5b, the exact commit this add-on builds — see build-neolink.yml):
`bind` / `bind_port` are FLAT TOP-LEVEL keys on the root Config struct, not nested
under any [[rtsp]] table. An earlier version of this file wrapped them in a
[[rtsp]] block, which this Config struct has no field for — Neolink silently
ignored it and fell back to its hardcoded defaults (0.0.0.0:8554,
see default_bind_addr()/default_bind_port() in config.rs), meaning the
"internal-only" bind documented below was never actually in effect. Re-verify
against src/config.rs whenever NEOLINK_COMMIT changes in build-neolink.yml — don't
assume TOML shape from memory again.

Neolink binds on an internal, non-public port — see restream_gen.py for why: go2rtc
is meant to be the sole real client, republishing to the outside world (Frigate,
VLC, etc.) on the public port this add-on has always used.

TEMPORARY: bind address reverted to 0.0.0.0 (was 127.0.0.1). With loopback-only
binding, BOTH go2rtc's client (which never sends OPTIONS before DESCRIBE) AND this
add-on's own OPTIONS-first probe got an identical, persistent "RTSP/1.0 404 Not
Found" on DESCRIBE — reproduced across multiple restart cycles and minutes of a
stable run, ruling out a startup race and ruling out any client-side protocol
difference. Neolink's own permission/role source (gst/factory.rs, gst/server.rs)
was checked directly and looks internally consistent for anonymous access with no
configured users, so no obvious code bug was found there either. 0.0.0.0 is the
one remaining variable that has ever actually been proven to work (weeks of VLC
and Frigate access on the old public bind); reverting it here, on the still-
internal port 18554 (unknown to Frigate, not exposed as an add-on port), isolates
whether loopback binding itself is what broke this. If this fixes it, the
"internal-only" protection is weaker (0.0.0.0:18554 is technically reachable from
the LAN, not just this container) but the port is still non-public/undocumented,
which is a reasonable interim trade-off over a completely non-functional stream.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path
from .store import Camera

log = logging.getLogger("aio-neolink.config_gen")

NEOLINK_CONFIG = Path(os.environ.get("NEOLINK_CONFIG", "/data/neolink.toml"))
# go2rtc is meant to be the only real client. Port deliberately far from go2rtc's
# own default ports (1984 API, 8554 RTSP, 8555 WebRTC) to avoid any collision.
RTSP_BIND_ADDR = os.environ.get("NEOLINK_RTSP_BIND_ADDR", "0.0.0.0")
RTSP_PORT = int(os.environ.get("NEOLINK_RTSP_PORT", "18554"))


def _render_camera(cam: Camera) -> str:
    lines = ["[[cameras]]", f'name = "{cam.name}"']
    if cam.uid:
        # Battery camera: UDP discovery by UID; no address needed.
        lines.append(f'uid = "{cam.uid}"')
    else:
        # Wired camera: direct Baichuan TCP address.
        lines.append(f'address = "{cam.address}:{cam.port}"')
    lines.append(f'username = "{cam.username}"')
    lines.append(f'password = "{cam.password}"')
    # B400/D400 single-stream cameras must pin a stream; omit for dual-stream ("both").
    if cam.stream in ("mainStream", "subStream"):
        lines.append(f'stream = "{cam.stream}"')
    return "\n".join(lines)


def render(cameras: list[Camera]) -> str:
    """Render a complete neolink.toml for the given cameras.

    `bind` / `bind_port` are flat top-level TOML keys (confirmed against
    src/config.rs — see module docstring). They are NOT nested under a [[rtsp]]
    table; that was a real bug in an earlier version of this file that silently
    left Neolink bound to its default 0.0.0.0:8554 regardless of these settings.
    """
    lines = [
        "# Generated by aio-neolink — do not edit by hand.",
        "# Regenerated every time a camera is added/edited via the GUI.",
        "",
        f'bind = "{RTSP_BIND_ADDR}"',
        f"bind_port = {RTSP_PORT}",
        "",
    ]
    enabled = [c for c in cameras if c.enabled]
    blocks = [_render_camera(c) for c in enabled]
    if not blocks:
        log.info("no enabled cameras; neolink.toml will have no [[cameras]] blocks")
    return "\n".join(lines) + "\n\n".join(blocks) + ("\n" if blocks else "")


def write(cameras: list[Camera], path: Path = NEOLINK_CONFIG) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(cameras))
    return path
