"""Generate neolink.toml from the camera store.

Neolink reads a TOML config describing the RTSP bind and one [[cameras]] block per
camera. We render it from the store so the GUI never makes the user touch TOML by hand.

TOML schema targets the QuantumEntangledAndy fork (0.6.x) which is what the original
"Neolink-latest" add-on ships. Verify against your exact binary if upgrading:
  neolink rtsp --config /dev/null --help

Neolink binds LOCALHOST ONLY, on an internal-only port — see restream_gen.py for why:
go2rtc is the sole client that ever connects to it, and go2rtc republishes to the
outside world (Frigate, VLC, etc.) on the public port this add-on has always used.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path
from .store import Camera

log = logging.getLogger("aio-neolink.config_gen")

NEOLINK_CONFIG = Path(os.environ.get("NEOLINK_CONFIG", "/data/neolink.toml"))
# Internal-only: go2rtc is the only thing that ever connects here. Deliberately far
# from go2rtc's own default ports (1984 API, 8554 RTSP, 8555 WebRTC) to avoid any
# collision with them.
RTSP_BIND_ADDR = os.environ.get("NEOLINK_RTSP_BIND_ADDR", "127.0.0.1")
RTSP_PORT = int(os.environ.get("NEOLINK_RTSP_PORT", "18554"))


def _render_camera(cam: Camera) -> str:
    lines = ["[[cameras]]", f'name = "{cam.name}"']
    if cam.uid:
        # Battery camera: UDP discovery by UID; no address needed.
        lines.append(f'uid = "{cam.uid}"')
    else:
        # Wired camera: direct Baichuan TCP address.
        lines.append(f'address = "{cam.address}:{cam.port}"')
    lines.append(f'username = "{cam.username}"')
    lines.append(f'password = "{cam.password}"')
    # B400/D400 single-stream cameras must pin a stream; omit for dual-stream ("both").
    if cam.stream in ("mainStream", "subStream"):
        lines.append(f'stream = "{cam.stream}"')
    return "\n".join(lines)


def render(cameras: list[Camera]) -> str:
    """Render a complete neolink.toml for the given cameras.

    The QuantumEntangledAndy 0.6.x fork uses a top-level [[rtsp]] section for the
    bind address. Older upstream Neolink used a flat `bind =` key — adjust here if
    your binary reports a different version.
    """
    lines = [
        "# Generated by aio-neolink — do not edit by hand.",
        "# Regenerated every time a camera is added/edited via the GUI.",
        "",
        "[[rtsp]]",
        f'bind = "{RTSP_BIND_ADDR}"',
        f"bind_port = {RTSP_PORT}",
        "",
    ]
    enabled = [c for c in cameras if c.enabled]
    blocks = [_render_camera(c) for c in enabled]
    if not blocks:
        log.info("no enabled cameras; neolink.toml will have no [[cameras]] blocks")
    return "\n".join(lines) + "\n\n".join(blocks) + ("\n" if blocks else "")


def write(cameras: list[Camera], path: Path = NEOLINK_CONFIG) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(cameras))
    return path
